# frozen_string_literal: true

source "https://rubygems.org"

# Using a fixed version/ref will not work with automatic updates because the
# version is checked using a list of refs at
# https://github.com/dependabot/dependabot-core.git/info/refs?service=git-upload-pack
# They are so many, our reference won't be found for it to be updated.
# Hence adding the branch.

# gem "dependabot-omnibus", github: "dependabot/dependabot-core", branch: "main"
gem "dependabot-omnibus", "~>0.228.0"

group :test do
  gem "rspec"
  gem "rubocop"
  gem "rubocop-performance"
  gem "vcr"
  gem "webmock"
end
