name: Infrastructure

on:
  push:
    branches: [main]
    paths:
      - deploy/**
      - .github/workflows/iac.yml
  pull_request:
    branches: [main]
    paths:
      - deploy/**
      - .github/workflows/iac.yml
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # wait for previous runs to complete on main and tags
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' && !startsWith(github.ref, 'refs/tags/') }}

env:
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}

jobs:
  Build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload Artifact (deploy)
        uses: actions/upload-artifact@v4
        with:
          path: deploy
          name: deploy
          retention-days: 1

      - name: Azure Login
        if: ${{ github.event_name == 'pull_request' }}
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Validate Azure Resources
        if: ${{ github.event_name == 'pull_request' }}
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: '${{ env.AZURE_RESOURCE_GROUP }}'
          template: '${{ github.workspace }}/deploy/main.bicep'
          scope: 'resourcegroup'
          deploymentMode: 'Validate'

  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    if: ${{ github.event_name != 'pull_request' }}
    timeout-minutes: 15

    concurrency:
      group: ${{ github.workflow }}

    steps:
      - name: Download Artifact (deploy)
        uses: actions/download-artifact@v4
        with:
          name: deploy
          path: deploy

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Azure Resources
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ env.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: '${{ env.AZURE_RESOURCE_GROUP }}'
          template: '${{ github.workspace }}/deploy/main.bicep'
          scope: 'resourcegroup'
